# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?


import math

count,ctr,n=0,0,0

def no_factors(n):
	pass
	f=2
	if n%int(math.sqrt(n))==0:
		pass
		f+=1
	for x in xrange(2,int(math.sqrt(n))):
		pass
		if n%x==0:
			pass
			f+=2
	return f

while count<500:
	pass
	ctr+=1
	n+=ctr
	count=no_factors(n)

print n